### ISSUE TITLE
`LAGOON_ROUTE` not generated when project has only autogenerated routes

### ISSUE THREAD

**Issue by cdchris12** [uselagoon/build-deploy-tool#42]
When calling the build-deploy tool as part of a Lagoon build to identify the environment's primary ingress, if the environment has only autogenerated routes, the primary ingress (and thus, the `LAGOON_ROUTE`) variable, will be empty. The `LAGOON_ROUTES` variable, however, will be populated with the project's autogenerated routes as expected.

Reading through the code, it seems that an autogenerated route can never be used as an environment's primary ingress. Specifically, https://github.com/uselagoon/build-deploy-tool/blob/e2903e02fe9dfe6ab2e645633a894c4b70a82317/cmd/identify_ingress.go#L112 only checks main routes if there is at least one main route already defined. It seems to me like we need to add an `else` block to that statement, which injects the first item from the array of autogenerated routes into the array of main routes if the array of main routes is empty.

**Comment by shreddedbacon** [comment]
Fixed in v0.9.1 but need to confirm against real world test as well.

**Comment by shreddedbacon** [comment]
Just for reference, the issue was with broken `docker-compose.yml` files. The build tool collects information from various places to get a `known state` of a build before it processes things, part of this is collecting the services from compose.

When the docker-compose file can't be read properly (due to invalid compose spec, or just generally bad yaml), this will break the build tool. This error was previously captured silently and not actually reporting the error, so it wasn't obvious. There are additional tests covering this now, with purposely broken docker-compose files matching ones that were reported as failing in builds from various customers. The error is actually captured now too.

**Comment by shreddedbacon** [comment]
Closing this as it is solved in v0.9.1 by using the compose-go library.
