### ISSUE TITLE
Add IngressClass (and possible required annotations) to ingress creation process

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/build-deploy-tool#70]
As of Kubernetes 1.19 - both ingress-nginx and traefik require the presence of an IngressClass resource on created Ingresses if they are required to operate on a non-default Ingress.

Lagoon doesn't currently support this for workloads - to make this happen, we need three things - a feature flag (that can be set at the controller or proj/env level), a resource created in the ingress and any relevant Annotations (e.g. certmanager).  The first two are pretty straightforward - but we would have to find a way to define the annotation that needs setting as they may differ if people don't use certmanager?

**Comment by shreddedbacon** [comment]
We can just assume the certmanager annotation is required, so it can be added if the class is defined. Lagoon routes allow for custom annotations already, so if a user was using something else that required a custom annotation, they could add it there. We would have to document this as a requirement.

Alternatively, the `LAGOON_ROUTES_JSON` could have an override added instead of in the `.lagoon.yml` as annotations are supported there too. Thoughts?
